brand: "uc"
format:
  typst:
    template: ../../../../templates/doc_template.typ
    # AGREGA ESTO (ajusta el nombre del archivo si es necesario):
    logo_file: "../../../../templates/UC COLOR-01.png"
  beamer:
    theme: metropolis
    header-includes: |
      \definecolor{PrimaryColor}{RGB}{0, 118, 192}
      \setbeamercolor{frametitle}{bg=PrimaryColor, fg=white}
      \setbeamercolor{progress bar}{fg=PrimaryColor, bg=gray}
      \titlegraphic{\hfill\includegraphics[height=1.2cm]{../../../../templates/UC COLOR-01.png}}
      