brand: "uc"

format:
  html:
    other-links:
      - text: "ðŸ“¥ Apunte UC (PDF)"
        href: "Apunte_UC.pdf"
        icon: file-pdf
      - text: "ðŸ“Š Slides UC (PDF)"
        href: "Slides_UC.pdf"
        icon: file-slides

  typst:
    output-file: "Apunte_UC.pdf"
    template: ../../../../templates/doc_template.typ
  
  beamer:
    output-file: "Slides_UC.pdf"
    theme: metropolis
    # Inyectamos colores UC a LaTeX (Beamer)
    header-includes: |
      \definecolor{PrimaryColor}{RGB}{0, 118, 192}   % Azul UC
      \definecolor{SecondaryColor}{RGB}{255, 209, 0} % Amarillo UC
      \setbeamercolor{frametitle}{bg=PrimaryColor, fg=white}
      \setbeamercolor{progress bar}{fg=SecondaryColor, bg=gray}
      \setbeamercolor{alerted text}{fg=PrimaryColor}
      \titlegraphic{\hfill\includegraphics[height=1.2cm]{UC COLOR-01.png}}