brand: "personal"
format:
  typst:
    template: ../../../../templates/doc_template.typ
    logo_file: "../../../../templates/logo.png" 
  beamer:
    theme: metropolis
    header-includes: |
      \definecolor{PrimaryColor}{RGB}{10, 40, 70}
      \setbeamercolor{frametitle}{bg=PrimaryColor, fg=white}
      \setbeamercolor{progress bar}{fg=PrimaryColor, bg=gray}
      \titlegraphic{\hfill\includegraphics[height=1.2cm]{../../../../templates/logo.png}}