brand: "personal"

format:
  html:
    other-links:
      - text: "ðŸ“¥ Apunte Personal (PDF)"
        href: "Apunte_Personal.pdf"
        icon: file-pdf
      - text: "ðŸ“Š Slides Personal (PDF)"
        href: "Slides_Personal.pdf"
        icon: file-slides

  typst:
    output-file: "Apunte_Personal.pdf"
    template: ../../../../templates/doc_template.typ
  
  beamer:
    output-file: "Slides_Personal.pdf"
    theme: metropolis
    # Inyectamos colores de TU MARCA a LaTeX (Beamer)
    header-includes: |
      \definecolor{PrimaryColor}{RGB}{10, 40, 70} % Azul Oscuro Logo
      \setbeamercolor{frametitle}{bg=PrimaryColor, fg=white}
      \setbeamercolor{progress bar}{fg=PrimaryColor, bg=gray}
      \setbeamercolor{alerted text}{fg=PrimaryColor}